# Generated by Django 5.1.4 on 2025-03-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaces',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('ON the way', 'ON the way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='pending...', max_length=20),
        ),
    ]
